// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package me.maxpeng.demo.server;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.maxpeng.demo.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
